### ISSUE TITLE
sem_scal_loss always decreases first and then increases

### ISSUE THREAD

**Issue by 807660937** [astra-vision/MonoScene#38]
Thank you for your work.
I find sem_scal_loss always decreases first and then increases. Is there some explanation here?
![image](https://user-images.githubusercontent.com/23006385/207521605-a7f05d5e-03c8-401f-b61c-e2350a578b40.png)

**Comment by anhquancao** [comment]
Hi @807660937, I didn't investigate it. One possible guess is that the sem_scal_loss overfit to the statistic of the training scene.
