### ISSUE TITLE
source of the NYUv2 dataset 

### ISSUE THREAD

**Issue by kebijuelun** [astra-vision/MonoScene#40]
Thanks for the wonderful work.

I wonder if you can provide the original source of the nyuv2 dataset, because I am confused about the depth data reading. The depth data is stored in the png format of uint16. I don't know how to convert this data to absolute metric depth data（in meters）. 

BTW, I found the depth transformation func in this toolkit does not match the data in this repo
http://cs.nyu.edu/~silberman/code/toolbox_nyu_depth_v2.zip

```
% Parameters for making depth absolute.
depthParam1 = 351.3;
depthParam2 = 1092.5;
function imgDepthAbs = depth_rel2depth_abs(imgDepthOrig)
  assert(isa(imgDepthOrig, 'double'));

  [H, W] = size(imgDepthOrig);
  assert(H == 480);
  assert(W == 640);

  camera_params;

  imgDepthAbs = depthParam1 ./ (depthParam2 - imgDepthOrig);
  
  imgDepthAbs(imgDepthAbs > maxDepth) = maxDepth;
  imgDepthAbs(imgDepthAbs < 0) = 0;
end
```
Look forward to your reply. Thanks.

**Comment by anhquancao** [comment]
Hi @kebijuelun, I took the dataset and the code to read it from here
https://github.com/waterljwant/SSC#data-preparation

**Comment by kebijuelun** [comment]
> Hi @kebijuelun, I took the dataset and the code to read it from here https://github.com/waterljwant/SSC#data-preparation

Thanks for the information!
Found that the correct transformation maybe:
`depth = imageio.imread(depth_filename) / 8000.0`


reference to:
[LINK1](https://github.com/waterljwant/SSC/blob/master/dataloaders/dataloader.py#L138)
[LINK2](https://github.com/shurans/sscnet/blob/c8699e18263f54083bb837b8fa67570b5710b050/caffe_code/caffe3d_suncg/src/caffe/layers/suncg_fusion.hpp#L45)

**Comment by anhquancao** [comment]
Great! Thanks for the info. I also remembered a number like that.
