### ISSUE TITLE
baselines reproduce

### ISSUE THREAD

**Issue by hitcslj** [astra-vision/MonoScene#42]
Thanks for this great work, I am terribly sorry to bother you with this issue.I found it hard to use these baselines.If possible,could you output your config and script for these baseline.

<img width="463" alt="image" src="https://user-images.githubusercontent.com/59784949/209709163-f20c13e8-39eb-4d07-b7ab-1e7c777f0a54.png">

**Comment by anhquancao** [comment]
Hi @hitcslj, can you give me your email so that I can send you my uncleaned code for these baselines.

**Comment by hitcslj** [comment]
Thank you @anhquancao ,my email is 2498065510@qq.com.

**Comment by anhquancao** [comment]
Hi @hitcslj, I sent it

**Comment by songw-zju** [comment]
Hi @anhquancao , I'm also interested in the implementation of these baselines. Would you mind sending me the code? My email is [songw_cs@qq.com](mailto:songw_cs@qq.com). Thanks for your kind consideration.

**Comment by wondervictor** [comment]
Hi @anhquancao, thanks for your awesome work, could you share me with the code of these baselines? (My email is thch@hust.edu.cn).

**Comment by anhquancao** [comment]
Hi, 
I uploaded the unclean code here
https://github.com/anhquancao/monoscene_unclean
For JS3CNet, I modified on their official code base to train and predict.
I don't have the data and models for this project. It's been two years. The environment is the same as MonoScene.
Data can be generated following what I described in Sec A.1. 

You can take a look at [this file](https://github.com/anhquancao/xmuda-extend/blob/master/xmuda/train_baseline.py#L103)

The data generation code is in this folder:
https://github.com/anhquancao/xmuda-extend/tree/master/xmuda/common/data_gen

- [kitti_compute_2d3d_mapping.py](https://github.com/anhquancao/xmuda-extend/blob/master/xmuda/common/data_gen/kitti_compute_2d3d_mapping.py): Compute pixel-voxel mapping

- [kitti_depth2tsdf.py](https://github.com/anhquancao/xmuda-extend/blob/master/xmuda/common/data_gen/kitti_depth2tsdf.py): Generate TSDF from depth 

- [kitti_generate_occ_map.py](https://github.com/anhquancao/xmuda-extend/blob/master/xmuda/common/data_gen/kitti_generate_occ_map.py): Generate occupancy grid from predicted depth

- [kitti_generate_sketch.py](https://github.com/anhquancao/xmuda-extend/blob/master/xmuda/common/data_gen/kitti_generate_sketch.py): Generate sketch for 3D sketch

- [kitti_seg2d_to_pcd.py](https://github.com/anhquancao/xmuda-extend/blob/master/xmuda/common/data_gen/kitti_seg2d_to_pcd.py): Create semantic point cloud from 2D semantic prediction and depth map
