### ISSUE TITLE
SemanticKITTI test submission 

### ISSUE THREAD

**Issue by kebijuelun** [astra-vision/MonoScene#45]
Hi, 
  Thanks for the wonderful work. 
  Would you please provide the code for generating test sets on semantic kitti? I write a code for generating the result, but found that the details is not in line with expectations, because the car mIoU is 0. This maybe a problem of class maping.

![image](https://user-images.githubusercontent.com/29164878/212698386-91063bef-cd14-4337-add2-c544ce01c85a.png)

Look forward for your reply.

**Comment by anhquancao** [comment]
Hi @kebijuelun,
This is the code I used
```
import monoscene.data.semantic_kitti.io_data as SemanticKittiIO

def step(self, batch, step_type, metric, metric_fov):
        bs = len(batch['img'])
        loss = 0
        out_dict = self(batch)
        ssc_pred = out_dict['ssc']
        if step_type == "test" and self.save_data_for_submission:
            y_pred = ssc_pred.detach().cpu().numpy()
            inv_map = SemanticKittiIO.get_inv_map()
            root_path = '/gpfsscratch/rech/kvd/uyl37fq/test_pred/Our/sequences/{}/predictions'
            for idx in range(y_pred.shape[0]):
                pred_label = np.argmax(y_pred[idx], axis=0).reshape(-1)
                pred_label = inv_map[pred_label].astype(np.uint16)
                frame_id = batch['frame_id'][idx]
                sequence = batch['sequence'][idx]
                folder = root_path.format(sequence)
                os.makedirs(folder, exist_ok=True)
                save_path = os.path.join(folder, "{}.label".format(frame_id))
                with open(save_path, 'wb') as f:
                    pred_label.tofile(f)
                    print("saved to", save_path)
            return
```
io_data is [this file](https://github.com/astra-vision/MonoScene/blob/master/monoscene/data/semantic_kitti/io_data.py)

**Comment by kebijuelun** [comment]
> Hi @kebijuelun, Congrats! Your results look really good. This is the code I used
> 
> ```
> import monoscene.data.semantic_kitti.io_data as SemanticKittiIO
> 
> def step(self, batch, step_type, metric, metric_fov):
>         bs = len(batch['img'])
>         loss = 0
>         out_dict = self(batch)
>         ssc_pred = out_dict['ssc']
>         if step_type == "test" and self.save_data_for_submission:
>             y_pred = ssc_pred.detach().cpu().numpy()
>             inv_map = SemanticKittiIO.get_inv_map()
>             root_path = '/gpfsscratch/rech/kvd/uyl37fq/test_pred/Our/sequences/{}/predictions'
>             for idx in range(y_pred.shape[0]):
>                 pred_label = np.argmax(y_pred[idx], axis=0).reshape(-1)
>                 pred_label = inv_map[pred_label].astype(np.uint16)
>                 frame_id = batch['frame_id'][idx]
>                 sequence = batch['sequence'][idx]
>                 folder = root_path.format(sequence)
>                 os.makedirs(folder, exist_ok=True)
>                 save_path = os.path.join(folder, "{}.label".format(frame_id))
>                 with open(save_path, 'wb') as f:
>                     pred_label.tofile(f)
>                     print("saved to", save_path)
>             return
> ```
> 
> io_data is [this file](https://github.com/astra-vision/MonoScene/blob/master/monoscene/data/semantic_kitti/io_data.py)

Thanks for your reply, I have fix the class mapping code with your help!
