### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by SohaibAnwaar** [astra-vision/MonoScene#47]
Hi I tried running the  model but getting this error

```
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 4226) exited unexpectedly

```

Regenerate the code 

1. I am using docker so you can see all of the installed versions and package in docker file

```
docker pull sohaibanwaar/monoscene
# You need to pull the git and attach with docker volume using the command below
# repo path = Git clone path
docker run -it --gpus all -v <repo path>:/monoscene sohaibanwaar/nvidia-10.2-ubuntu-conda-python bash
```

Got error while Inference
```
python monoscene/scripts/generate_output.py \
    +output_path=$MONOSCENE_OUTPUT \
    dataset=NYU \
    NYU_root=$NYU_ROOT \
    NYU_preprocess_root=$NYU_PREPROCESS \
    n_gpus=1 batch_size=1
```

**Comment by anhquancao** [comment]
Hi @SohaibAnwaar,
I think it's because the data loader workers use too much memory. You can set a smaller number of workers here
https://github.com/astra-vision/MonoScene/blob/master/monoscene/scripts/eval_monoscene.py#L26

**Comment by SohaibAnwaar** [comment]
> Hi @SohaibAnwaar, I think it's because the data loader workers use too much memory. You can set a smaller number of workers here https://github.com/astra-vision/MonoScene/blob/master/monoscene/scripts/eval_monoscene.py#L26

solved Thank you
