### ISSUE TITLE
Dataloader not loading data

### ISSUE THREAD

**Issue by SohaibAnwaar** [astra-vision/MonoScene#48]
hi @anhquancao 
Can you please help here why Dataloader is not picking up the data

Command
```
python monoscene/scripts/generate_output.py     +output_path=$MONOSCENE_OUTPUT     dataset=NYU     NYU_root=$NYU_ROOT     NYU_preprocess_root=$NYU_PREPROCESS     n_gpus=1 batch_size=1
```

Result
```
NYU ROOT /monoscene/nyu/NYU_dataset/depthbin/
NYU PREPROCESS ROOT /monoscene/nyu/NYU_dataset/depthbin/preprocess
NYU FRUSTUM SIZE 8
NYU BATCH SIZE 1
NYU NUM WORKERS 1
n_relations 4
Using cache found in /root/.cache/torch/hub/rwightman_gen-efficientnet-pytorch_master
Loading base model ()...Done.
Removing last two layers (global_pool & classifier).
Building Encoder-Decoder model..Done.
0it [00:00, ?it/s]
(monoscene) root@d0a
```

**Comment by anhquancao** [comment]
Hi @SohaibAnwaar,
Can you check what is the values of  **self.scan_names** in this line
https://github.com/astra-vision/MonoScene/blob/master/monoscene/data/NYU/nyu_dataset.py#L46
and if the folder **self.root** contains any ".bin" files?

**Comment by SohaibAnwaar** [comment]
sorry, mistake in my root path. Thanks for fask response.
I made a docker file and setup all required installment, Can you merge that docker file in this git. Please it will be help full for people. I will update commands in readme.

**Comment by anhquancao** [comment]
@SohaibAnwaar,
Amazing! Thank you a lot! Could you please make a pull request?

**Comment by SohaibAnwaar** [comment]
sure sure @anhquancao

**Comment by SohaibAnwaar** [comment]
@anhquancao Now I am trying with just 1 gpu_process, `segmentation fault` issue occurs again.

```
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 1464) exited unexpectedly
```

**Comment by anhquancao** [comment]
Can you try to traverse the dataset with a code like this?
```
 ds = NYUDataset(
        "train",
        root, # change to NYU_root
        preprocess_root, # change to NYU_preprocess_root
    )
    for i in range(len(ds)):
        ds[i]
```

**Comment by SohaibAnwaar** [comment]
![screenshot_26](https://user-images.githubusercontent.com/29427728/219880482-faac292f-5879-4344-a522-c18ee3d25344.png)
1. see my gpu is empty (left bottom window)
2. My CPU is empty (left top window)
3. Python space not left error when try to fetch from data_loader (right bottom window)

**Comment by anhquancao** [comment]
The problem is out of machine RAM, not the GPU memory.

**Comment by SohaibAnwaar** [comment]
Ahh, as you can see left bottom terminal is 'htop'

In that you can see that used memory is 14GB total memory is 32GB. 

I dont think its ram issue 🙌

**Comment by anhquancao** [comment]
I saw the error message "no space left on device". Any thoughts on why this happened? I don't think any data is written in the dataloader.

**Comment by anhquancao** [comment]
Can you test the dataset alone, without the dataloader? like this code
```
ds = NYUDataset(
        "train",
        root, # change to NYU_root
        preprocess_root, # change to NYU_preprocess_root
    )
for i in range(len(ds)):
      ds[i]
```

**Comment by SohaibAnwaar** [comment]
Emm, let me debug it. Also let me test dataset without loader ✅🙌

**Comment by SohaibAnwaar** [comment]
hi @anhquancao I debug the problem. `from torch.utils.data.dataloader import DataLoader` is creating a problem because of multi-processing

https://github.com/astra-vision/MonoScene/blob/32898e734caa50b9f78b04596a30f4bfa2b28964/monoscene/data/NYU/nyu_dm.py#L73

by removing the `num_workers` param from data loader the issue is fixed.

**Comment by anhquancao** [comment]
The num_workers is required for faster training, I don't think it should be removed

**Comment by SohaibAnwaar** [comment]
yes for that multi-GPUs are needed. not working on single GPU machine 😅

**Comment by anhquancao** [comment]
It is the number of CPU processes to process data. I don't see how it is related to number of GPUs?

**Comment by SohaibAnwaar** [comment]
I am not sure, But when-ever I try to give num_worker even 1. it fails saying segmentation error.

**Comment by SohaibAnwaar** [comment]
@anhquancao this is issue in pytorch 1.7.1.
https://github.com/pytorch/pytorch/issues/54752

**Comment by anhquancao** [comment]
The code was fine with pytorch 1.7.1, I think you should use the same version

**Comment by SohaibAnwaar** [comment]
yes, you are right, I use the same commands for installation. but don't know how version miss-match occurs. Thank for helping @anhquancao
