### ISSUE TITLE
About the results of val set

### ISSUE THREAD

**Issue by shuowang666** [astra-vision/MonoScene#53]
Hi, I tried to get the performance of Semantic Kitti in Tab3, but I only get mIoU of 10.7-11.0. I wonder if I want to get the mIoU of 11.5 as Tab3, what else should I do?

**Comment by shuowang666** [comment]
Thank you for your answer.  Could you share what I should modify to achieve your previous results?

**Comment by anhquancao** [comment]
Hi, I am sorry. I am not sure what caused the problem. I tried to get the previous results, but I wasn't able to get the same number. But I guess smth like more convolution layers, bigger layer dimension.

**Comment by shuowang666** [comment]
Thanks for your reply！
