### ISSUE TITLE
ValueError: `Dataloader` returned 0 length. Please make sure that it returns at least 1 batch

### ISSUE THREAD

**Issue by noeast1997** [astra-vision/MonoScene#55]
when I run :
python monoscene/scripts/train_monoscene.py     dataset=kitti     enable_log=true     kitti_root=/bigdata2/WD/SemanticKITTI/data_odometry_color     kitti_preprocess_root=/bigdata2/WD/SemanticKITTI/preprocess    kitti_logdir=$KITTI_LOG
this error exits:
ValueError: `Dataloader` returned 0 length. Please make sure that it returns at least 1 batch

Please help me,thanks!

**Comment by noeast1997** [comment]
I used the SemanticKITTI dataset:
![image](https://user-images.githubusercontent.com/102639018/224270863-6488fbaf-3e48-420e-a284-c6a90f182648.png)

**Comment by anhquancao** [comment]
Hi @noeast1997,
The path to the SemanticKITTI dataset should look like this
![image](https://user-images.githubusercontent.com/9668858/224275022-d0ba94e6-0a6f-4ccc-85f0-81233c60a9d2.png)
Note the **dataset** folder

**Comment by noeast1997** [comment]
I changed the path,
![image](https://user-images.githubusercontent.com/102639018/224290379-4e2a7442-4022-4b15-aa25-a9e9b512c86e.png)
but it still exits thiw error：
![image](https://user-images.githubusercontent.com/102639018/224290468-0614bcc4-ddfd-4271-9ef7-b7fc2a866a5c.png)

**Comment by anhquancao** [comment]
Hi, can you check if the glob_path in this line is correct?
https://github.com/astra-vision/MonoScene/blob/master/monoscene/data/semantic_kitti/kitti_dataset.py#L60
In each sequence directory, you need to have the **voxels** folder looks like this
`/home/acao/jeanzay/work/data/semantic_kitti/dataset/sequences/00/voxels`
This **voxels** part can be downloaded [here](http://www.semantic-kitti.org/dataset.html#download)
![image](https://user-images.githubusercontent.com/9668858/224291871-05c2e646-67ec-4bb1-b007-aef9f82d8981.png)

**Comment by noeast1997** [comment]
and **data_odometry_voxels** folder only has 02 folder right?
![image](https://user-images.githubusercontent.com/102639018/224291976-c42b3815-be1b-491c-9fa2-5c20f9448513.png)

**Comment by anhquancao** [comment]
You should have more
![image](https://user-images.githubusercontent.com/9668858/224292270-8dd60e8e-fc37-4898-aa3c-c7074eb55c45.png)

**Comment by noeast1997** [comment]
Thanks a lot, I ran train_monoscene.py successfully. I didn't put all the files in a dataset file before, and an error occurred when downloading the voxel file.
In the preprocess.py file,I changed:LABEL = remap_lut[LABEL.astype(np.uint16)].astype(np.float32) to LABEL = remap_lut[LABEL.astype(np.uint32)].astype(np.float64) ,this should not affect overall operation.

Thanks again so much!

**Comment by anhquancao** [comment]
You're welcome! I'm glad to hear that. Thanks for your information!
