### ISSUE TITLE
hello! I found some codes are exactly the same. Are they reduplicate?

### ISSUE THREAD

**Issue by Yuankus** [astra-vision/MonoScene#56]
here in the self.downsample3 and self.downsample4 in the pic. In MonoScene/monoscene/models/DDR.py line 100

**Comment by Yuankus** [comment]
Sorry that I made some mistake! I can understand it now! Thanks!

**Comment by anhquancao** [comment]
Hello, @Yuankus! Indeed, a more appropriate approach would involve using a for loop with a ModuleList.
