### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by 13629281511** [astra-vision/MonoScene#57]
Hi, when I try to evaluate the your provided trained model on NYUv2, by the way all prepared work has been done follow repo guidance, it occurs the following issue:
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
Then, I check the error and found the inputs of module MonoScene.forward() : batch(list) which contain img, mask and so no. All variables in this list are on "cpu" not "gpu". Could you please help me to solve the problem?

**Comment by anhquancao** [comment]
Hi @13629281511, can you elaborate on which line of code the error occurs and which command did you run?

**Comment by 13629281511** [comment]
I run the command `python monoscene/scripts/eval_monoscene.py \
    dataset=NYU \
    NYU_root=$NYU_ROOT\
    NYU_preprocess_root=$NYU_PREPROCESS \
    n_gpus=1 batch_size=1`, and the error occurred at [(https://github.com/astra-vision/MonoScene/blob/b3b12cf7e0df12cf68b95b0cc39f1d9ef1041666/monoscene/models/monoscene.py#L91)](url)

**Comment by 13629281511** [comment]
Yes, I think I find the error and have fixed it. Now, the evaluation command can normally run. Thanks a lot!
