### ISSUE TITLE
Inference on other datasets

### ISSUE THREAD

**Issue by Alex-Hanzh** [astra-vision/MonoScene#58]
Hello authors, first of all thank you for your great work and open source initiative. I want to apply your work on the CVUSA dataset, but I tested it with the demo you put on the hugging face, and the result is not good, can you please help me with this issue? Could you please provide me with some guidance on how to improve the performance of the model?

**Comment by anhquancao** [comment]
Hi @Alex-Hanzh, you need to retrain the method on your dataset. The model on HuggingFace demo is trained on SemanticKITTI dataset. Thus, it overfitted to the camera parameters and the scenery of SemanticKITTI.

**Comment by Alex-Hanzh** [comment]
Due to the lack of 3D semantic annotation in the CVUSA dataset, I am confused about how to train the model on this dataset. Can I improve the performance of the model on this dataset by modifying camera parameters? If possible, could you please give me some guidance on which parts to modify

**Comment by anhquancao** [comment]
Hi @Alex-Hanzh, The current method requires 3D annotation. I don't think it can work without retraining

**Comment by Alex-Hanzh** [comment]
> Hi @Alex-Hanzh, The current method requires 3D annotation. I don't think it can work without retraining

Got it! Thanks for your help

**Comment by Alex-Hanzh** [comment]
> Hi @Alex-Hanzh, The current method requires 3D annotation. I don't think it can work without retraining

Got it! Thanks for your help
