### ISSUE TITLE
Modeling from video taken by myself

### ISSUE THREAD

**Issue by noeast1997** [astra-vision/MonoScene#61]
Is it possible to model from a video taken by myself？

**Comment by anhquancao** [comment]
Hi @noeast1997, I think you can split the video into frames and predict frame by frame.

**Comment by noeast1997** [comment]
Does modeling only need RGB images, or does it need other information such as image depth and camera pose?
Thank you so much！

**Comment by anhquancao** [comment]
Only RGB image is required for inference. However, for training, you need the 3D semantic ground-truth. You don't need the camera pose if the ground-truth is already in the camera coordinate.

**Comment by noeast1997** [comment]
I once tried to take an RGB picture for modeling, but the modeling effect was not satisfactory. I wondered if it was not trained a lot for similar scenes.

**Comment by anhquancao** [comment]
Yes, the model learns prior of the trained scene, so if the image is too different from the training ones in terms of camera parameters and type of scenery, it will not generalize well.
