### ISSUE TITLE
Class label meanings

### ISSUE THREAD

**Issue by sparsh-b** [astra-vision/MonoScene#62]
Hello,

Where can I find the look-up table for the correspondence between class label number (being predicted [here](https://github.com/astra-vision/MonoScene/blob/853f4ead3a584147b9968f7f2ed2d8296d0da909/monoscene/scripts/visualization/NYU_vis_pred.py#L147)) and class name? For example, what class does a class label number of 3 correspond to?

Note:
I've found in the NYUv2 [paper](https://cs.nyu.edu/~silberman/papers/indoor_seg_support.pdf) that the dataset has 894 different object classes. But it looks like MonoScene is predicting only 12 classes (from the size of the tensor [here](https://github.com/astra-vision/MonoScene/blob/853f4ead3a584147b9968f7f2ed2d8296d0da909/monoscene/scripts/generate_output.py#L93)).

Thanks for actively monitoring the issues!

**Comment by anhquancao** [comment]
Hi @sparsh-b ,
I took the data from here 
https://github.com/waterljwant/SSC#Data-Preparation

You can find the class label here
https://github.com/waterljwant/SSC/blob/master/config.py#L9

For ground-truth generation, please check Sec. 5, second paragraph in the first SSC paper https://arxiv.org/pdf/1611.08974v1.pdf

**Comment by sparsh-b** [comment]
For class labels, you mean Line27 ryt?
https://github.com/waterljwant/SSC/blob/master/config.py#L27

Thanks!

**Comment by anhquancao** [comment]
Yes
