### ISSUE TITLE
Stuck in generate_output.py loop

### ISSUE THREAD

**Issue by hidetatz** [astra-vision/MonoScene#64]
Hi, I am trying to run MonoScene but it seems like the output process does not start.
This is the console output.

```
$ python monoscene/scripts/generate_output.py     +output_path=$MONOSCENE_OUTPUT     dataset=NYU     NYU_root=$NYU_ROOT     NYU_preprocess_root=$NYU_PREPROCESS     n_gpus=1 batch_size=1
n_relations 4
Downloading: "https://github.com/rwightman/gen-efficientnet-pytorch/archive/master.zip" to /home/hidetatz/.cache/torch/hub/master.zip
Downloading: "https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/tf_efficientnet_b7_ns-1dbc32de.pth" to /home/hidetatz/.cache/torch/hub/checkpoints/tf_efficientnet_b7_ns-1dbc32de.pth
Loading base model ()...Done.
Removing last two layers (global_pool & classifier).
Building Encoder-Decoder model..Done.
  0%|                                                                                                                                                                              | 0/654 [00:00<?, ?it/s]
```

The progress bar at the bottom line never starts. I did some print debug and made sure [this loop](https://github.com/astra-vision/MonoScene/blob/master/monoscene/scripts/generate_output.py#L90) is not starting.

Do you have some suggestion what I should try?

**Comment by hidetatz** [comment]
Thank you, I tried that but the result does not change. By the way, I tried the same procedure on another pc, it resulted the segmentation fault.
I am debugging some GPU related places but please tell me if you still have some suggestions.

**Comment by hidetatz** [comment]
I changed num_workers to 0, then the inference started!
I think I can close the issue now. Thank you for your help.

**Comment by anhquancao** [comment]
Great! I'm pleased to hear that. Thank you for sharing that information.
