### ISSUE TITLE
About visualization code

### ISSUE THREAD

**Issue by joonsu0109gh** [astra-vision/MonoScene#69]
I'm attempting to use your visualization code, and I have a few questions. In this image, the 'fov_mask' and 'camera line' don't seem to be exactly the same. Which one is more precise?

![image](https://github.com/astra-vision/MonoScene/assets/73662370/3c20e234-9e02-4849-9036-6591a85d1121)

**Comment by anhquancao** [comment]
Hello,
The FOV mask is more correct. I made the camera bigger to visualize better.

**Comment by joonsu0109gh** [comment]
Thank you!

**Comment by joonsu0109gh** [comment]
Thank you for your prompt response. 
I have one more question, could I ask you for detailed values of the precise image pixel coordinates, or is there a specific reference I should use?

**Comment by anhquancao** [comment]
I don't understand your question. 
The FOVs voxels are computed by projecting all voxels on the image and checking if the projected pixels are inside and in front of the image (depth) > 0.
 The camera FOV is just a pentahedron. I took the 4 pixels at the corners of the image, fix a depth value for them then unproject them into 3D. They are the 4 corners of the pentahedron. The last corner is the camera position.

**Comment by joonsu0109gh** [comment]
I apologize for causing confusion. What I want to ask is how I can get the precise 3D coordinates of the corners of an image.

**Comment by anhquancao** [comment]
You can take a look at [this code.](https://github.com/astra-vision/MonoScene/blob/master/monoscene/scripts/visualization/kitti_vis_pred.py#L46)

**Comment by joonsu0109gh** [comment]
I've already looked at that code, and it seemed to me that the image corner coordinates obtained through the code are different from the image location that can be indirectly verified through the FOV. 
That's why I asked the first question. You answered that the camera was made larger for visualization, so I asked how I can obtain the precise coordinates of the camera corner.
Thank you for answer.

**Comment by anhquancao** [comment]
I think you need to set [d](https://github.com/astra-vision/MonoScene/blob/master/monoscene/scripts/visualization/kitti_vis_pred.py#L43)=distance from camera to the image plane.
http://www.cs.toronto.edu/~jepson/csc420/notes/imageProjection.pdf

But in KITTI, f is in pixel unit so probably you need to find a way to convert it back to meter.
