### ISSUE TITLE
Pretrained UNet2D

### ISSUE THREAD

**Issue by hongxiaoy** [astra-vision/MonoScene#70]
I have one question when reproduce the model, is the EfficientNet frozen when training?

**Comment by anhquancao** [comment]
Hi @hongxiaoy, it is not frozen during training.

**Comment by hongxiaoy** [comment]
OK, thanks for your reply! I was faced a problem with nan loss in my own dataset. I'll check it again.

**Comment by AniketDhar** [comment]
I want to confirm something that logically makes sense to me. 
As per my understanding, the UNet2D module is a semantic segmentation module. Is it possible to replace this by an instance segmentation module to get instance information in the final 3D voxel grid? If yes, what other changes could be required in the pipeline?
