### ISSUE TITLE
How to choose voxel origin in real world

### ISSUE THREAD

**Issue by zhyzhyzhy123** [astra-vision/MonoScene#71]
Hey, I am trying to apply the model of NYUv2 into the real indoor enviroment. But I have trouble with `voxel origin`, how should I choose a proper `voxel origin`? I choose `(0,0,0)`, which result in an bad result. Thank you.

**Comment by anhquancao** [comment]
Hi @zhyzhyzhy123,
Thanks for using our code! You can take a look at this [issue](https://github.com/astra-vision/MonoScene/issues/59).

**Comment by zhyzhyzhy123** [comment]
Hi @anhquancao , Thank you for your reply, I have read through the issue, is that meaning the model which is pretrained can not be used directly? Cause I do not have enough data to retrain the model XD.

**Comment by anhquancao** [comment]
In fact, NYUv2 is very small dataset with ~1500 images for both train + val.

**Comment by zhyzhyzhy123** [comment]
Thanks for your reply, I make some effort on model working on my own rgb image. But I have some trouble with `vox_origin`, I found voxel origin greatly influences the results of the model. And I have no idea how to decide the voxel origin, do you know how can I decide the voxel origin of my own image? Thanks a lot.

**Comment by anhquancao** [comment]
If you are reconstructing in camera coordinates (as shown in the provided image) and you want the scene to have dimensions of (dx, dy, dz) with the camera positioned at the center of one side of the scene, then the voxel origin should be set to (-dx/2, -dy/2, dz). Please carefully checking the orientation of the axes in your camera coordinates, as they may differ.

![image](https://github.com/astra-vision/MonoScene/assets/9668858/d27b26c8-c361-4b04-ab06-7a0f7daea2be)

**Comment by zhyzhyzhy123** [comment]
Thanks a lot, I am new in this area. What you said scene dimension, is that the scene size?

**Comment by zhyzhyzhy123** [comment]
Thanks for your help, I think I got a little bit understood!
