### ISSUE TITLE
Different of carmera intrinsic parameters

### ISSUE THREAD

**Issue by zhyzhyzhy123** [astra-vision/MonoScene#74]
Hi, when I download the NYUv2 dataset, there is a toolbox. Where I found the RGB intrinsic parameters is as follow
```
% RGB Intrinsic Parameters
fx_rgb = 5.1885790117450188e+02;
fy_rgb = 5.1946961112127485e+02;
cx_rgb = 3.2558244941119034e+02;
cy_rgb = 2.5373616633400465e+02;
```
But in `nyu_dataset.py`, the `cam_k`(which I think is the intrinsic parameters) is `np.array([[518.8579, 0, 320], [0, 518.8579, 240], [0, 0, 1]])`. Is there any transformation between these two parameters?

**Comment by anhquancao** [comment]
Hello, the fx, fy, cx, cy is indeed from the intrinsic matrix param as following:
np.array([[fx, 0, cx], 
                [0, fy, cy], 
                [0, 0, 1]])

**Comment by zhyzhyzhy123** [comment]
yep, I know, this is from https://github.com/astra-vision/MonoScene/blob/6ba72f9c27cabcb910eee82db1c72d112c5163f6/monoscene/data/NYU/nyu_dataset.py#L40
but, when I check the NYUv2 dataset in the [offical website](https://cs.nyu.edu/~silberman/datasets/nyu_depth_v2), in Download part, there is a Toolbox, where in it, a file named `camera_params.m` indicate the  parameters as I metioned. I do not know what cause these difference.

**Comment by anhquancao** [comment]
They are the same?  5.1885790117450188e+02 == 518.8597
the cx and cy is slightly smaller because the image is cropped (cx, cy are half image size).

**Comment by zhyzhyzhy123** [comment]
Thanks for your reply, what I am not understanding is the fy value, it is different and fy is the same with the fx XD

**Comment by anhquancao** [comment]
I think probably it doesn't really change anything, You can set to the original value. I use the value from the other works like 3DSketch and AICNet.

**Comment by zhyzhyzhy123** [comment]
thanks for your reply! I guess it won't change anything. Thanks a lot!
