### ISSUE TITLE
Transfer to new dataset.

### ISSUE THREAD

**Issue by hongxiaoy** [astra-vision/MonoScene#75]
I'm sorry to bother you again. I'm trying to use your model in the ScanNet dataset, specifically I use one frame of rgb image in each scene and voxelized the whole scene acoording to the point cloud, and I also keep those voxels in camera fov. However, I have trained the monoscene model for about 30 epochs with 1201 train samples and 312 val samples. The miou is only 4.9, and when I visualzed the result it predicts empty voxels to other semantics most often, just like the picture below. Do you have some advice to such a situation? Thanks you very much!
![predict](https://github.com/astra-vision/MonoScene/assets/112234465/9f79775a-e2eb-4174-a5dc-550f51d36751)
![target](https://github.com/astra-vision/MonoScene/assets/112234465/6a8a5b82-9a29-4ce2-9684-6fb9025cda39)

**Comment by anhquancao** [comment]
Hello @hongxiaoy, I believe the issue may be related to the fact that the weight of the empty class is too low. Could you try to increase it and see if that yields better results?"

**Comment by hongxiaoy** [comment]
Thanks for your advice, I have a try.

**Comment by hongxiaoy** [comment]
> Hello @hongxiaoy, I believe the issue may be related to the fact that the weight of the empty class is too low. Could you try to increase it and see if that yields better results?

This method seems not work. Is there any possibility that when I use this model into my own constructed datasets for practical use, the model not work that good.

**Comment by anhquancao** [comment]
I suggest you to try to overfit on single sample to see if the model can memorize it. I think there is a probably a bug somewhere.

**Comment by anhquancao** [comment]
The mIoU of 30 for overfitting seems quite low. Normally, it should be able to achieve a very high mIoU on a single example. 
You might also want to consider trying another method, such as the one available here: https://github.com/Jiawei-Yao0812/NDCScene.
