### ISSUE TITLE
prepare custom data for training

### ISSUE THREAD

**Issue by yyash-patel** [astra-vision/MonoScene#76]
Hello @anhquancao ,

I really liked the work! I wanted to train using my own custom data therefore to know **how I can generate ground-truth data and labels**. I saw that you provided the steps in #30, but didn't understand much.

Thanks,
Yash

**Comment by anhquancao** [comment]
Hi @yyash-patel , I suggest you to take a look at this repo https://github.com/jbehley/voxelizer to generate ground-truth.  The voxelized ground-truth is already provided in the Semantic KITTI dataset.

**Comment by yyash-patel** [comment]
Thanks, I will check it out !
