### ISSUE TITLE
How to test monoscene on semantic KITTI

### ISSUE THREAD

**Issue by luang321** [astra-vision/MonoScene#77]
In semantic KITTI test sequences don't have .label files thus its' preprocess folder also doesn't have .npy files. But in the code  ,the testloader still try to load the .npy files and try to use SSCMetrics class to evaluate the results like train/val, which of course won't work. 
So is the test script available?  Could you please provide the test script in the code. That will be much appreciated, thank you.

**Comment by anhquancao** [comment]
Hey there! There is no test label, you need to submit it to the online server for evaluating on test set.

**Comment by luang321** [comment]
> Hi! There is no test label, you need to submit it to the online server for evaluating on test set.

Yes， I mean the test script is not included in the code. and the test part of the code is wrong.  So I mean it will be much appreciated if you could also include a script to generate the result to be submitted to the server. Haha

**Comment by anhquancao** [comment]
Hi, I didn't keep the test script, you can adapt [this code](https://github.com/astra-vision/LMSCNet/blob/main/LMSCNet/test.py) from LMSCNet to generate the test result.

**Comment by luang321** [comment]
> Hi, I didn't keep the test script, you can adapt [this code](https://github.com/astra-vision/LMSCNet/blob/main/LMSCNet/test.py) from LMSCNet to generate the test result.
Ok, Thank you!
