### ISSUE TITLE
feature line of sight >> infer own custom image using NYU pretrained model

### ISSUE THREAD

**Issue by yyash-patel** [astra-vision/MonoScene#78]
Hi @anhquancao ,

In this issue - #7, I follow the necessary steps to infer a single image. But I face an issue, what happens is - 

At the stage of implementing the feature line of sight (flosp.py), the output from -
https://github.com/astra-vision/MonoScene/blob/d62849d17f86570fb914bfd7ea3487cee94c1a3a/monoscene/models/flosp.py#L23-L32

If I use the NYU dataset the output of **src_feature** has shape [200,129600] which is then reshaped to [200,60,36,60], because full scene size is 60,36,60.

But when I use my own custom image the shape of **src_feature** is (200,1382400), this creates a dimension issue since it's not consistent with the scene size provided i.e. [60,36,60].

Please guide me with this !

Thanks,
Yash

**Comment by anhquancao** [comment]
Hey @yyash-patel! Make sure to update the scene parameters to match your specific scene dimensions. Here's the link where you'll find the current settings: https://github.com/astra-vision/MonoScene/blob/d62849d17f86570fb914bfd7ea3487cee94c1a3a/monoscene/data/NYU/nyu_dataset.py#L37.

You'll want to adjust these variables to fit your data:
```
self.voxel_size = 0.08  # 0.08m
self.scene_size = (4.8, 4.8, 2.88)  # (4.8m, 4.8m, 2.88m)
self.img_W = 640
self.img_H = 480
self.cam_k = np.array([[518.8579, 0, 320], [0, 518.8579, 240], [0, 0, 1]])
 
```

**Comment by yyash-patel** [comment]
oh okay thanks ! I passed wrong parameters.
