### ISSUE TITLE
Under what path should these data sets be placed?

### ISSUE THREAD

**Issue by yuan243212790** [astra-vision/MonoScene#79]
In what path should these data sets be placed to function properly?

**Comment by jackwky** [comment]
我也有相同的疑问，而且我用了那个预处理命令，感觉不太对。
![SA{G9AKNGKWG7N7TGM4X5J](https://github.com/astra-vision/MonoScene/assets/126163628/b6c87f14-ca46-4fca-8931-eef9564629a9)

**Comment by jackwky** [comment]
> 你好！您可以尝试在此处打印sequence_path变量以查看它们是否正确。 https://github.com/astra-vision/MonoScene/blob/master/monoscene/data/semantic_kitti/preprocess.py#L58

好的 我成功解决了 感谢

**Comment by yuan243212790** [comment]
这个问题我已解决，但是可视化ｋｉｔｔｉ是第三视角的，不是论文展示的这样的第一视角，这个应该如何调整

**Comment by anhquancao** [comment]
Sorry, I don't speak Chinese. I don't understand your question? I think we showed third view in the paper.
