### ISSUE TITLE
about backbone

### ISSUE THREAD

**Issue by luang321** [astra-vision/MonoScene#84]
As mentioned in the paper, monoscene's backbone is a 2d unet based on efficientnetb7 , but efficientnet b7 have 64m parameters and the unet decoder part have an extra 69m  that makes up more than 88% of the total 149m parameters. In my experiment, when trained on KItti dataset, I found it really difficult to train monoscene without OOM on a single V100  32G  with batch size greater than 1. But in the paper, monoscene is trained with 2 batches per gpu. Is the decoder part in backbone necessary to reproduce the result in the paper? should I set the use_decoder to False? Thank you.

**Comment by anhquancao** [comment]
Hello @luang321 , I think the 88% increase is from the 3D encoder-decoder. However, I can train monoscene on NYUv2 with batch size of 2 on a single V100-32G since NYU scene size is only 60x36x60.
